#Server
server:
  servlet:
    context-path: /comparador

#DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motos
    username: first
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
  devtools:
    remote:
      secret: 123

#flyway:
#  schema: motos
#  url: jdbc:mysql://localhost:3306
#  baseline-on-migrate: true