#DataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motos
    username: first
    password: 123456789

#spring.jpa.hibernate.dll-auto=update

#
  jpa:
    show-sql: true
#
  devtools:
    remote:
      secret: 123

#flyway:
#  schema: motos
#  url: jdbc:mysql://localhost:3306
#  baseline-on-migrate: true